<?php
/**
* @about: The main navigation menu is generated by this script, based on the folder structure of the content folder.
* 
* 
* PHP version 5.4
*
* @version          2.0 - 30/01/2017
* @package          This file is part of QDP - QUICK DEVELOPMENT PACKAGE - THE DATABASE FREE CMS
* @copyright        (C) 2017 Gyula Soós
* @license          This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* See LICENSE.txt for copyright notices and details.
*/

defined('QDP') or die('Restricted access');

function createMenu($activePage){

    #$dir = array_slice(scandir(rootFolder.'/content'),2); //scan the main content folder and store all 1st level folders
    $dir = array_slice(scandir(rootFolder.'/content/'.'/'.siteLanguage),2);

    //the unordered list is started and closed in the template
    foreach ($dir as $key => $value) { //for each folder, check if there are subfolders
        if (is_dir(rootFolder.'/content/'.siteLanguage.'/'.$value)){ //if a folder is found in a subfolder

    $lookForFiles = array_slice(scandir(rootFolder.'/content/'.siteLanguage.'/'.$value),2);         //scan for every folder inside the parent   
            foreach ($lookForFiles as $files => $file) { //remove the entries that are folders
                if (is_dir(rootFolder.'/content/'.siteLanguage.'/'.$value.DIRECTORY_SEPARATOR.$file)){
                    unset($lookForFiles[$files]);
                }
            }

            if (substr($value,0, 2) == "00"){//lay down the start of the li tag
                echo "\t\t\t<li><a href='".siteDomain."'".isActive($activePage, $value).'>'.substr($value, 3)."</a>";
            } elseif (count($lookForFiles) == 0){
                    echo "\t\t\t<li class='notARealLink'>".isActive($activePage, $value).substr($value, 3);
            } else {
                echo "\t\t\t<li><a href='".siteDomain.urlencode($value)."'".isActive($activePage, $value).">".substr($value, 3)."</a>";
            }
            
            $subdir = array_slice(scandir(rootFolder.'/content/'.siteLanguage.'/'.$value),2);         //scan for every folder inside the parent   
            foreach ($subdir as $item => $itemValue) { //remove the entries that are not folders
                if (!is_dir(rootFolder.'/content/'.siteLanguage.'/'.$value.DIRECTORY_SEPARATOR.$itemValue)){
                    unset($subdir[$item]);
                }
            }
            
            if (sizeof($subdir) > 0){ //if folders found, create a sub list
                echo "\n\t\t\t<ul>\n";  //start another ul list
                foreach ($subdir as $subkey => $subvalue) {   //for each subfolder
                    if (is_dir(rootFolder.'/content/'.siteLanguage.'/'.$value.DIRECTORY_SEPARATOR.$subvalue)){         //and only if it's a folder (not a file)          
                       echo "\t\t\t\t<li><a href='".siteDomain.urlencode($value)."/".urlencode($subvalue)."'>".substr($subvalue,3)."</a></li>";
                    }
                }
                echo "</ul>\n"; //then close the ul for the sub-items
            }
              echo "\n\t\t\t</li>\n"; //close the original list item

        }
    }
}

    function isActive($page, $active){  //this function will be called with two parameters: the pagename, and what page is active. this information is generated by the pagename script
        if ($page == "wwwroot" or $page == "root"){

            $page = "00.".$langSettings["homeName"]; 
        }
        
        if ($page == $active) {
            return ' class="active" ';    //if the pagename and the active page are matching, then, the link will be marked as active
        } else {
            return '';
        }
    }
?>