<?php
/**
* @about: Create menu for the backend
* 
* PHP version 5.4
*
* @version          1.0 - 06/03/2016
* @package          This file is part of QDP - QUICK DEVELOPMENT PACKAGE - THE DATABASE FREE CMS
* @copyright        (C) 2016 Gyula Soós
* @license          This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* See LICENSE.txt for copyright notices and details.
*/

defined('QDP') or die('Restricted access');
function createMenu($activePage){

    //scaning the admincontent folder for folders. Non folders will be removed. Display each found folder as a link on the backend menustrip
    $dir = array_slice(scandir(adminRootFolder.DS.'adminContent'),2); //scan the main content folder and store all 1st level folders

    foreach ($dir as $key => $value) { //for each folder, check if there are subfolders
        if (is_dir(adminRootFolder.DS.'adminContent'.DS.$value)){ //if a folder is found in a subfolder
            $lookForFiles = array_slice(scandir(adminRootFolder.DS.'adminContent'.DS.$value),2);         //scan for every folder inside the parent   
            foreach ($lookForFiles as $files => $file) { //remove the entries that are folders
                if (is_dir(adminRootFolder.DS.'adminContent'.DS.$value.DIRECTORY_SEPARATOR.$file)){
                    unset($lookForFiles[$files]);
                }
            }   

            if ($value == "00.Home"){//lay down the start of the li tag
                echo '<li '.isActive($activePage, $value).'><a href="'.siteDomain.'">'.substr($value, 3).'</a>';
            } else {
                echo '<li '.isActive($activePage, $value).'><a href="'.siteDomain.urlencode($value).'">'.substr($value, 3).'</a>';
            }
            echo '</li>'; //close the original list item
        }
    }
}

function isActive($page, $active){  //this function will be called with two parameters: the pagename, and what page is active. this information is generated by the pagename script
    if ($page == ""){
        $page = "00.Home"; 
    }

    if ($page == $active) {
        return ' class="active" ';    //if the pagename and the active page are matching, then, the link will be marked as active
    } else {
        return '';
    }
}

?>